[package]
name = "rivetlua"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "RivetLua 的公開 Rust SDK。"
readme = "README.md"

[dependencies]
rivetlua-core = { path = "../rivetlua-core" }
rivetlua-compiler = { path = "../rivetlua-compiler" }
rivetlua-runtime = { path = "../rivetlua-runtime" }
