[package]
name = "rivetlua-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "RivetLua 的受控命令列介面。"

[features]
default-lua54 = []

[dependencies]
rivetlua = { path = "../rivetlua" }

[target.'cfg(any(unix, windows))'.dependencies]
cpu-time = "=1.0.0"

[[bin]]
name = "rivetlua"
path = "src/bin/rivetlua.rs"

[[bin]]
name = "rivetluac"
path = "src/bin/rivetluac.rs"
